type SidebarTab = {
	DASHBOARD: string;
	NETWORKS: string;
	CONTACT: string;
	NETWORK: string;
	STATISTICS: string;
	INTEGRATIONS: string;
};

const TABS: SidebarTab = {
	DASHBOARD: "DASHBOARD",
	NETWORKS: "NETWORKS",
	NETWORK: "NETWORK",
	STATISTICS: "STATISTICS",
	CONTACT: "CONTACT",
	INTEGRATIONS: "INTEGRATIONS",
};

export { TABS };
